import fs from "node:fs";
import path from "node:path";
import type { Project } from "@arqen/core";
export type FindingSeverity = "critical" | "high" | "medium" | "low" | "info";
export type FindingCategory = "hierarchy" | "spacing" | "typography" | "color" | "density" | "consistency" | "responsive" | "accessibility" | "interaction" | "navigation" | "decoration" | "component_architecture" | "design_system";
export type FindingRisk = "low" | "medium" | "high";
export type FindingCertainty = "CERTAIN" | "LIKELY" | "POSSIBLE";
export interface Finding { id: string; category: FindingCategory; severity: FindingSeverity; confidence: number; certainty: FindingCertainty; risk: FindingRisk; title: string; evidence: string; recommendation: string; potentialFix?: string; files: string[]; rule: string; }
export interface AuditResult { score: number; scoreModel: { base: number; penalties: Record<FindingSeverity, number>; explanation: string }; findings: Finding[]; summary: { critical: number; high: number; medium: number; low: number; info: number }; }
const UI_EXTENSIONS = /\.(tsx|jsx|ts|js|css|scss|sass)$/;
const severityPenalty: Record<FindingSeverity, number> = { critical: 20, high: 12, medium: 7, low: 3, info: 0 };
function uiFiles(project: Project): string[] { return project.files.filter((file) => UI_EXTENSIONS.test(file.extension)).map((file) => path.join(project.root, file.path)); }
function relativeFiles(project: Project, predicate?: (file: Project["files"][number]) => boolean): string[] { return project.files.filter((file) => UI_EXTENSIONS.test(file.extension) && (!predicate || predicate(file))).map((file) => file.path); }
function add(findings: Finding[], finding: Omit<Finding, "id">) { findings.push({ ...finding, id: `${finding.rule}:${findings.length + 1}` }); }
function confidence(value: number) { return Math.max(0, Math.min(1, value)); }
export function auditProject(project: Project): AuditResult {
  const findings: Finding[] = []; const files = uiFiles(project); let allSource = "";
  for (const file of files) { try { allSource += `\n${fs.readFileSync(file, "utf8")}`; } catch { /* snapshot may change */ } }
  const rounded = (allSource.match(/rounded-(?:lg|xl|2xl|3xl|full)/g) ?? []).length + (allSource.match(/border-radius\s*:/g) ?? []).length;
  if (rounded >= 12) add(findings, { category: "decoration", severity: "medium", confidence: confidence(Math.min(0.96, 0.55 + rounded / 100)), certainty: "LIKELY", risk: "low", title: "High concentration of rounded containers", evidence: `${rounded} rounded-container declarations or utilities were detected.`, recommendation: "Reserve larger radii for controls or intentional surfaces; use a smaller structural radius scale where appropriate.", potentialFix: "Review the largest repeated radii and replace only redundant structural uses with existing tokens.", files: relativeFiles(project), rule: "decoration.rounded-containers" });
  const gradients = (allSource.match(/(?:bg-gradient|linear-gradient|radial-gradient)/g) ?? []).length;
  if (gradients >= 3) add(findings, { category: "decoration", severity: "low", confidence: 0.78, certainty: "LIKELY", risk: "low", title: "Repeated decorative gradients", evidence: `${gradients} gradient declarations were found.`, recommendation: "Keep gradients that communicate identity or state; remove decorative gradients only when they dilute hierarchy.", files: relativeFiles(project), rule: "decoration.gradients" });
  const shadows = (allSource.match(/(?:shadow-(?:sm|md|lg|xl|2xl)|box-shadow\s*:)/g) ?? []).length;
  if (shadows >= 10) add(findings, { category: "decoration", severity: "low", confidence: 0.82, certainty: "LIKELY", risk: "low", title: "Shadow density may dilute hierarchy", evidence: `${shadows} shadow declarations were found.`, recommendation: "Define a small elevation scale and reserve stronger shadows for overlays and meaningful separation.", files: relativeFiles(project), rule: "decoration.shadow-density" });
  const arbitrarySpacing = [...allSource.matchAll(/(?:p|m|gap|space-[xy])-\[(\d+(?:\.\d+)?)(?:px|rem)\]/g)];
  if (arbitrarySpacing.length >= 5) add(findings, { category: "spacing", severity: "medium", confidence: 0.9, certainty: "CERTAIN", risk: "medium", title: "Many one-off spacing values", evidence: `${arbitrarySpacing.length} arbitrary spacing utilities were detected.`, recommendation: "Prefer the project's existing spacing scale when visual intent does not require an exception.", potentialFix: "Map repeated arbitrary values to the nearest established spacing token after contextual review.", files: relativeFiles(project), rule: "spacing.arbitrary-values" });
  const buttons = (allSource.match(/<button\b/g) ?? []).length + (allSource.match(/(?:Button|button)-(?:primary|secondary|ghost|outline|default)/g) ?? []).length;
  if (buttons >= 8) add(findings, { category: "hierarchy", severity: "medium", confidence: 0.62, certainty: "POSSIBLE", risk: "medium", title: "Action hierarchy should be reviewed", evidence: `${buttons} button declarations or variant references were detected. Static analysis cannot prove visual coherence.`, recommendation: "Audit primary, secondary and tertiary actions across screens and keep one clear dominant treatment per context.", files: relativeFiles(project), rule: "hierarchy.button-variants" });
  const responsive = (allSource.match(/(?:sm|md|lg|xl):/g) ?? []).length + (allSource.match(/@media\s*\(/g) ?? []).length + (allSource.match(/@container\s*\(/g) ?? []).length;
  if (project.framework !== "unknown" && responsive < 3 && project.files.length > 5) add(findings, { category: "responsive", severity: "high", confidence: 0.58, certainty: "POSSIBLE", risk: "high", title: "Limited explicit responsive behavior", evidence: `Only ${responsive} responsive utility, media-query or container-query signals were found. This is a signal, not proof that responsive behavior is missing.`, recommendation: "Verify mobile and tablet layouts. Add analyzer adapters for other responsive mechanisms when present.", files: relativeFiles(project), rule: "responsive.low-signal" });
  const fixedWidths = [...allSource.matchAll(/(?:width|min-width|max-width)\s*:\s*(\d{3,4})px/g)].map((match) => Number(match[1] ?? 0)).filter((value) => value >= 320);
  const wideTailwind = (allSource.match(/(?:w|w-min|w-max)-\[(\d{3,4})px\]/g) ?? []).length;
  if (fixedWidths.length + wideTailwind >= 2) add(findings, { category: "responsive", severity: "medium", confidence: 0.83, certainty: "LIKELY", risk: "medium", title: "Potential fixed-width mobile overflow", evidence: `${fixedWidths.length + wideTailwind} large fixed-width declarations were detected. Static analysis cannot observe actual viewport overflow.`, recommendation: "Prefer fluid widths with max-width constraints and verify at narrow viewports.", potentialFix: "Replace only layout-critical fixed widths after checking intended desktop constraints.", files: relativeFiles(project), rule: "responsive.fixed-width-risk" });
  const overflowHidden = (allSource.match(/overflow-(?:hidden|clip)/g) ?? []).length; const horizontalFlex = (allSource.match(/(?:display:\s*flex|flex\b|flex-row|grid-cols-\d+)/g) ?? []).length;
  if (horizontalFlex >= 5 && overflowHidden >= 2) add(findings, { category: "responsive", severity: "low", confidence: 0.7, certainty: "POSSIBLE", risk: "medium", title: "Overflow rules may conceal responsive failures", evidence: `${horizontalFlex} layout signals coexist with ${overflowHidden} overflow-clipping signals.`, recommendation: "Verify clipped content and horizontal layouts at mobile widths rather than relying on overflow suppression.", files: relativeFiles(project), rule: "responsive.overflow-clipping" });
  const imageTags = (allSource.match(/<img\b/g) ?? []).length; const altAttrs = (allSource.match(/\balt\s*=/g) ?? []).length;
  if (imageTags > altAttrs) add(findings, { category: "accessibility", severity: "high", confidence: 0.93, certainty: "CERTAIN", risk: "medium", title: "Images may be missing alternative text", evidence: `${imageTags} img elements and ${altAttrs} alt attributes were detected.`, recommendation: "Give informative images meaningful alternative text and mark purely decorative images appropriately.", potentialFix: "Inspect each image before adding alt text; decorative assets may correctly use an empty alt value.", files: relativeFiles(project), rule: "accessibility.image-alt" });
  const controls = (allSource.match(/<(?:input|select|textarea)\b/g) ?? []).length; const labels = (allSource.match(/<label\b/g) ?? []).length + (allSource.match(/aria-label\s*=|aria-labelledby\s*=/g) ?? []).length;
  if (controls > labels) add(findings, { category: "accessibility", severity: "high", confidence: 0.86, certainty: "LIKELY", risk: "high", title: "Form controls may lack accessible names", evidence: `${controls} form controls and ${labels} explicit label/name signals were detected.`, recommendation: "Ensure every interactive form control has an accessible name through a label, aria-label, or aria-labelledby.", files: relativeFiles(project), rule: "accessibility.form-names" });
  const buttonBlocks = [...allSource.matchAll(/<button\b([^>]*)>([\s\S]*?)<\/button>/g)];
  const unnamedButtons = buttonBlocks.filter((match) => { const attrs = match[1] ?? ""; const body = match[2] ?? ""; const bodyWithoutHidden = body.replace(/<[^>]*aria-hidden=["']true["'][^>]*>[\s\S]*?<\/[^>]+>/gi, "").replace(/<[^>]+>/g, "").trim(); return !/aria-label\s*=|aria-labelledby\s*=/.test(attrs) && !bodyWithoutHidden; }).length;
  if (unnamedButtons > 0) add(findings, { category: "accessibility", severity: "high", confidence: 0.96, certainty: "CERTAIN", risk: "high", title: "Buttons without an accessible name", evidence: `${unnamedButtons} button elements contain no detectable text or accessible-name attribute.`, recommendation: "Give icon-only and otherwise unlabeled buttons an accessible name.", files: relativeFiles(project), rule: "accessibility.button-names" });
  const focusSignals = (allSource.match(/:focus(?:-visible|-within)?\b/g) ?? []).length + (allSource.match(/focus(?:-visible)?:/g) ?? []).length + (allSource.match(/onFocus\s*=|onKeyDown\s*=/g) ?? []).length; const interactiveCount = (allSource.match(/<(?:button|a|input|select|textarea)\b/g) ?? []).length;
  if (interactiveCount >= 5 && focusSignals === 0) add(findings, { category: "accessibility", severity: "medium", confidence: 0.79, certainty: "LIKELY", risk: "medium", title: "No explicit keyboard-focus styling detected", evidence: `${interactiveCount} interactive elements were detected with no static focus-state signal.`, recommendation: "Provide visible focus indicators and verify keyboard navigation in the browser.", files: relativeFiles(project), rule: "accessibility.focus-state" });
  const weakLinks = [...allSource.matchAll(/<a\b[^>]*>([\s\S]*?)<\/a>/g)].filter((match) => /^(?:here|click here|learn more|read more|more)$/i.test((match[1] ?? "").replace(/<[^>]+>/g, "").trim()));
  if (weakLinks.length > 0) add(findings, { category: "accessibility", severity: "medium", confidence: 0.94, certainty: "CERTAIN", risk: "low", title: "Links use weak accessible names", evidence: `${weakLinks.length} link labels rely on generic phrases such as “learn more” or “click here”.`, recommendation: "Use link text that identifies the destination or action without relying on surrounding context.", files: relativeFiles(project), rule: "accessibility.weak-link-names" });
  const headings = [...allSource.matchAll(/<h([1-6])\b/g)].map((match) => Number(match[1] ?? 1)); const headingJump = headings.some((level, index) => index > 0 && level - (headings[index - 1] ?? level) > 1);
  if (headingJump) add(findings, { category: "hierarchy", severity: "medium", confidence: 0.88, certainty: "CERTAIN", risk: "medium", title: "Heading hierarchy skips levels", evidence: `Heading sequence contains a jump larger than one level (${headings.join(" → ")}).`, recommendation: "Use heading levels to express document hierarchy rather than visual size alone.", files: relativeFiles(project), rule: "hierarchy.heading-levels" });
  const duplicatePatterns = project.designSystem.componentPatterns.filter((pattern) => pattern.count >= 3);
  if (duplicatePatterns.length > 0) add(findings, { category: "component_architecture", severity: "low", confidence: 0.84, certainty: "LIKELY", risk: "low", title: "Repeated component patterns detected", evidence: duplicatePatterns.slice(0, 5).map((pattern) => `${pattern.name} (${pattern.count} uses)`).join(", "), recommendation: "Review repeated UI patterns for shared component boundaries rather than one-off implementations.", files: [...new Set(duplicatePatterns.flatMap((pattern) => pattern.files))], rule: "components.repeated-patterns" });
  const explicitTokens = project.designSystem.tokens.filter((token) => !token.name.startsWith("repeated:"));
  if (explicitTokens.length === 0) add(findings, { category: "design_system", severity: "medium", confidence: 0.88, certainty: "CERTAIN", risk: "medium", title: "No explicit CSS design tokens detected", evidence: "No custom CSS variables were found in analyzed stylesheets.", recommendation: "Introduce a small token layer for recurring color, spacing, type, radius and elevation decisions before normalizing components.", potentialFix: "Create semantic tokens only after confirming repeated visual decisions in the source.", files: project.files.filter((file) => /\.(css|scss|sass)$/.test(file.extension)).map((file) => file.path), rule: "design-system.no-tokens" });
  const repeated = project.designSystem.repeatedValues.filter((item) => item.count >= 3);
  if (repeated.length === 0 && explicitTokens.length > 0) add(findings, { category: "design_system", severity: "low", confidence: 0.7, certainty: "POSSIBLE", risk: "low", title: "Design tokens show limited reuse", evidence: "Few extracted token values repeat across the project.", recommendation: "Review whether token names represent semantic roles and whether repeated decisions have been centralized.", files: [], rule: "design-system.low-reuse" });
  const penalties = { critical: 0, high: 0, medium: 0, low: 0, info: 0 }; for (const finding of findings) penalties[finding.severity] += severityPenalty[finding.severity];
  const score = Math.max(0, Math.min(100, 100 - Object.values(penalties).reduce((sum, value) => sum + value, 0))); const summary = { critical: 0, high: 0, medium: 0, low: 0, info: 0 }; for (const finding of findings) summary[finding.severity] += 1;
  return { score, scoreModel: { base: 100, penalties, explanation: "Score is a deterministic prioritization signal based on finding severity; it is not an objective measure of design quality." }, findings, summary };
}
